apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Release.Namespace }}-secret-reader
  labels:
    {{- include "parasol-store-build.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cross-namespace-secret-reader
subjects:
- kind: ServiceAccount
  name: {{ include "parasol-store-build.name" . }}-setup-sa
  namespace: {{ .Release.Namespace }}