apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: resync
spec:
  steps:
    - args:
        - >-
          oc delete deployment -n {{ .Release.Namespace }} -l
          app.kubernetes.io/instance=parasol-store-{{ .Values.gitlab.branch }}
      command:
        - /bin/bash
        - '-c'
      image: 'quay.io/openshift/origin-cli:latest'
      name: resync
      computeResources: {}
