---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ${{ values.component_id }}-${{ values.branch }}-build
  namespace: ${{ values.gitops_namespace }}
  finalizers:
    - resources-finalizer.argocd.argoproj.io/foreground
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  project: ${{ values.gitops_project }}
  source:
    repoURL: ${{ values.source_repository_gitops }}
    targetRevision: main
    path: ./helm/parasol-store-build
    helm:
      values: |
        backstage:
          id: ${{ values.component_id }}-${{ values.branch }}
        gitlab:
          host: ${{ values.gitlab_host }}
          group: ${{ values.gitlab_group }}
          project: ${{ values.gitlab_project }}
          branch: ${{ values.branch }}
        image:
          host: ${{ values.image_host }}
          namespace: ${{ values.image_organization }}
          name: ${{ values.image_name }}
          tag: ${{ values.image_tag }}
        cluster:
          subdomain: ${{ values.cluster_subdomain }}
  destination:
    server: https://kubernetes.default.svc
    namespace: ${{ values.namespace }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
      - ApplyOutOfSyncOnly=true
    managedNamespaceMetadata:
      labels:
        argocd.argoproj.io/managed-by: ${{ values.gitops_namespace }}
    retry:
      backoff:
        duration: 5s # the amount to back off. Default unit is seconds, but could also be a duration (e.g. "2m", "1h")
        factor: 2 # a factor to multiply the base duration after each failed retry
        maxDuration: 10m # the maximum amount of time allowed for the backoff strategy    